nerds-sh/hermes.api

- Readme.md
Create Readme file
[HER-34](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-34)
> [HER-34] Create readme file

- src/Presentation/Controller/Controller.cs
- src/Presentation/Presentation.csproj
- src/Presentation/Startup.cs
Create   "/v1/api/version" endpoint
[HER-31](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-31)
> [HER-31] Create version endpoint

- src/Presentation/Presentation.csproj
Reference Graphql package
[HER-26](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-26)
> [HER-26] Reference graph package

- Hermes.Api.sln
- src/Business/Business.csproj
- src/Data/Data.csproj
- src/Presentation/Presentation.csproj
Create business project
[HER-29](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-29)
> [HER-29] Create business project

- src/Data/Context.cs
- src/Data/Data.csproj
- src/Data/EDetections.cs
- src/Presentation/Presentation.csproj
- src/Presentation/Settings/settings.default.json
- src/Presentation/Startup.cs
[HER-41](https://nerds-interns.atlassian.net/browse/HER-41?atlOrigin=eyJpIjoiMjRkMWQwYjUyZmJmNDA3YjgzYTAzNTkwZDNmYzg1ZjAiLCJwIjoiaiJ9)
> [HER-41] Configure database connection

- src/Business/Models/MDetection.cs
- src/Data/Data.csproj
- Create MDetection model
- It should live inside business layer
[HER-50](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-50)
> [HER-50] Create business model

- dockerfile.release
- scripts/docker.build.release.py
- src/Business/Business.csproj
- src/Data/Data.csproj
- src/Presentation/Presentation.csproj
- src/Presentation/Status/Controller.cs
- Be able to show branch in informational version
- Be able to show sha inside informational version
All the related jira tickets for the current pull request.
- [HER-58](https://nerds-interns.atlassian.net/browse/HER-58)
> [HER-58] Configure informational version

- src/Business/Models/MDetection.cs
Rename the `timestep` field to `timestamp`
[HER-55](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-55)
> [HER-55] Fix typo in business model

- Readme.md
- scripts/docker.run.dependencies.py
Create a script that start hermes-db dependency from docker-compose
[HER-44](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-44)
> [HER-44] Create dependencies script

- src/Business/Models/MDetection.cs
Change class type to string from object
[HER-60](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-60)
> [HER-60]Change class field type

- src/Business/Detection/Models/MDetection.cs
- src/Business/Detection/Repositories/IDetection.cs
- src/Business/Detection/Repositories/IDetectionRepository.cs
- Create detection repository interface
- It should live inside business layer
- It shouldn't be referenced anywhere yet
- It should contain a single method
- All -> IEnumerable<MDetection>
[HER-51](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-51)
> [HER-51] Create business repository

- src/Presentation/Detection/Common/Types/TDetection.cs
- src/Presentation/Detection/Creating/IResolver.cs
- src/Presentation/Detection/Creating/Resolver.cs
- src/Presentation/Detection/Fetching/IResolver.cs
- src/Presentation/Detection/Fetching/Resolver.cs
- src/Presentation/GraphQL/Base/Query.cs
- src/Presentation/GraphQL/Base/Schema.cs
- src/Presentation/Startup.cs
Create query with mocked data
[HER-49](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-49)
> [HER-49] Create detections query 

- src/Business/Detection/Fetching/Commands/IGetDetection.cs
- src/Presentation/Detection/Creating/IResolver.cs
- src/Presentation/Detection/Fetching/IResolver.cs
- src/Presentation/Startup.cs
Remove unused imports
[HER-63](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-63)
> [HER-63] Remove unused imports

- src/Business/Detection/Common/Models/MCreateDetection.cs
- src/Business/Detection/Creating/Models/MCreateDetection.cs
- Create model (MCreateDetection) under the business project
- Class
- Score
- Timestamp
[HER-68](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-68)
> [HER-68] Create business input

- src/Presentation/Detection/Creating/IResolver.cs
- src/Presentation/Detection/Creating/Resolver.cs
- src/Presentation/GraphQL/Base/Mutation.cs
- src/Presentation/GraphQL/Base/Schema.cs
Create detection mutation inside Presentation
[HER-70](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-70)
> [HER-70] Create detection mutation

- test/Data.UnitTests/Detection/DetectionFactoryTests.cs
- test/Directory.Build.props
- test/StyleCop.json
- test/StyleCop.ruleset
- Configure stylecop rules 
- Reference stylecop packages
- Include stylecop in all test projects
All the related jira tickets for the current pull request.
- [HER-74](https://nerds-interns.atlassian.net/browse/HER-74)
> [HER-74] Configure test stylecop

- src/Data/Detection/DetectionFactory.cs
- src/Data/Detection/DetectionRepository.cs
- src/Presentation/Startup.cs
- test/Data.UnitTests/Detection/DetectionFactoryTests.cs
Create "Insert" method
[HER-72](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-72)
> [HER-72] Change data repository

- src/Business/Pagination/PPagination.cs
- It will leave inside Pagination Directory in Business
- It will have pageSize and pageIndex as components (int)
[HER-75](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-75)
> [HER-75] Create pagination parameter

- src/Presentation/Detection/Creating/IResolver.cs
- src/Presentation/Detection/Creating/Resolver.cs
- src/Presentation/Detection/Creating/Types/TCreateDetection.cs
- src/Presentation/GraphQL/Base/Mutation.cs
- src/Presentation/GraphQL/Base/Query.cs
- Invoke the business command from inside the detections mutation
- Register business command inside IoC
- Ensure the entity inserted in the database
- Make sure to configure the input parameter
[HER-73](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-73)
> [HER-73] Connect detection mutation

- src/Business/Pagination/MPagination.cs
- it wll leave inside Pagination Directory in Business
- it will have a list of items, pageSize,pageIndex,totalCount as properties
[HER-77](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-77)
> [HER-77] Create pagination model

- src/Business/Detection/Common/Models/PDetection.cs
- src/Business/Detection/Fetching/Models/PDetection.cs
- it will leave inside Model Directory in Business
- it will have id,score,class,timestamp and PPagination as properties
[HER-76](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-76)
> [HER-76] Create detection parameter

- src/Business/Business.csproj
- src/Business/Camera/Common/Models/MCamera.cs
-     it will live inside business layer
-     it will be used as a return type for our business command
-     it will contain:
- id
- longitude
- latitude
[HER-80](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-80)
> [HER-80] Create camera business model

- src/Business/Camera/Register/Models/MRegisterCamera.cs
- it will live inside business layer
- it will be used as an input type for our business command
- it will contain: id, latitude, longitude
[HER-81](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-81)
> [HER-81] Create camera business input

- src/Business/Camera/Fetching/Models/PCamera.cs
- it will have the ids field
- it will not be nullable but it can be empty 
[HER-86](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-86)
> [HER-86] Create camera parameter

- src/Presentation/Camera/Common/Types/TCamera.cs
It will live inside Presentation layer
It will contain the following fields:
- Id
- Longitude
- Latitude
It will be used as a return type for Register camera Mutation
[HER-78](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-78)
> [HER-78] Create camera graph type

- src/Business/Detection/Creating/Models/MCreateDetection.cs
[HER-92](https://nerds-interns.atlassian.net/browse/HER-92?atlOrigin=eyJpIjoiM2M5MTMxZWM4YzU1NDIyMTliMGZlZmYxOWY3NGE5NGEiLCJwIjoiaiJ9)
> [HER-92] Change create detection input

- src/Presentation/Camera/Register/Types/TRegisterCamera.cs
- It will live inside Presentation Layer
- It’s going to be used as an input for out Create Register Camera Mutation
- It has the following fields: Latitude, Longitude, Id ( chrome device identifier )
[HER-79](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-79)
> [HER-79] Create camera graph input

- src/Business/Business.csproj
- src/Business/Detection/Common/Models/MDetection.cs
- Add Camera field to MDetection
[HER-97](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-97)
> [HER-97] Change the detection model

- src/Business/Detection/Fetching/Models/PDetection.cs
- Add CameraId field to PDetections
- It will be used by the command
[HER-95](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-95)
> [HER-95] Change detections parameter

- src/Data/Detection/DetectionFactory.cs
- src/Data/Detection/DetectionRepository.cs
- src/Data/EDetection.cs
- src/Data/Migrations/20210726094855_AlterDetectionAddCameraIdField.Designer.cs
- src/Data/Migrations/20210726094855_AlterDetectionAddCameraIdField.cs
- src/Seeds/Data/detections.json
-Modify detection factory so it contains CameraId
-Add CameraId field in Entity
-Ensure that a migration is created
[HER-93](https://nerds-interns.atlassian.net/browse/HER-93?atlOrigin=eyJpIjoiZTE3YjBhMjAxMzg0NGU4NjgwMjQ1M2I4YzE1ZDc0NzIiLCJwIjoiaiJ9)
> [HER-93] Change detection repository

- src/Presentation/Detection/Creating/Types/TCreateDetection.cs
[HER-91](https://nerds-interns.atlassian.net/browse/HER-91?atlOrigin=eyJpIjoiMDhmZjExMzBkOTI4NDhjMDlkNTRlMWE2NDk4OTRlYTQiLCJwIjoiaiJ9)
> [HER-91] Change create detection graph input

- src/Business/Camera/Common/Repositories/ICameraRepository.cs
- src/Data/Camera/CameraFactory.cs
- src/Data/Camera/CameraRepository.cs
- src/Presentation/Startup.cs
- test/Data.UnitTests/Camera/CameraFactoryTest.cs
It will live inside data layer
It will be used for fetching and creating cameras by business command
Configure camera factory
Create insert method
[HER-82](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-82)
> [HER-82] Create camera repository

- src/Business/Camera/Common/Repositories/ICameraRepository.cs
- src/Data/Camera/CameraRepository.cs
- src/Data/Camera/Filtering/CameraFilter.cs
- src/Data/Camera/Filtering/ICameraFilter.cs
- src/Presentation/Startup.cs
-    it will live inside the Data layer
-    it will receive a PCamera
-    it will return an IEnumerable<MCamera>
-    it will be used by the business command
[HER-89](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-89)
> [HER-89] Configure fetching in camera repository

- src/Data/Camera/CameraRepository.cs
Change CameraFilter to ICameraFilter in CameraRepository constructor
[HER-103](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-103)
> [HER-103] Fix camera repository

- src/Business/Detection/Common/Models/MDetection.cs
- src/Business/Detection/Common/Repositories/IDetectionRepository.cs
- src/Business/Detection/Fetching/Commands/GetDetection.cs
- src/Business/Detection/Fetching/Commands/IGetDetection.cs
- src/Business/Detection/Fetching/Models/PDetection.cs
- src/Data/Camera/CameraRepository.cs
- src/Data/Detection/DetectionFactory.cs
- src/Data/Detection/DetectionRepository.cs
- src/Data/Detection/Entities/EDetection.cs
- src/Data/Detection/Filtering/DetectionFilter.cs
- src/Data/Detection/Filtering/IDetectionFilter.cs
- src/Presentation/Detection/Fetching/Resolver.cs
- src/Presentation/Startup.cs
- test/Data.UnitTests/Detection/DetectionFactoryTests.cs
- add filter to the fetch method
- add Camera field to entity
- change detection factory
[HER-96](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-96)
> [HER-96] Change detections repository

- src/Presentation/Detection/Common/Types/TDetection.cs
- Add Camera field to TDetection
[HER-98](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-98)
> [HER-98] Change detection graph type

- src/Presentation/Pagination/Types/TPPagination.cs
- it will contain page size and page index fields
[HER-100](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-100)
> [HER-100] Create pagination graph type

- src/Presentation/Pagination/Types/TPagination.cs
-    it should live inside Presentation layer
-    it should contain the following fields: 
- list of generic items 
- page size
- page index 
- total counts
[HER-99](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-99)
> [HER-99] Create pagination graph type

- src/Presentation/Camera/Fetching/Factory.cs
- src/Presentation/Camera/Fetching/IResolver.cs
- src/Presentation/Camera/Fetching/Resolver.cs
- src/Presentation/GraphQL/Base/Query.cs
- src/Presentation/Startup.cs
-it will live inside the Presentation layer
-it will be used by the GraphQL
-it will call the command method
[HER-88](https://nerds-interns.atlassian.net/browse/HER-88?atlOrigin=eyJpIjoiNmY5NGRlN2Q1YWQ5NDljNWI2MTNmNDBkZWFhNTI3YzAiLCJwIjoiaiJ9)
> [HER-88] Create cameras query

- src/Business/Detection/Common/Models/MDetection.cs
- src/Business/Detection/Creating/Models/MCreateDetection.cs
- src/Business/Detection/Fetching/Models/PDetection.cs
- src/Data/Detection/DetectionRepository.cs
- src/Data/Detection/Entities/EDetection.cs
- src/Data/Migrations/20210728134138_AlterDetectionsChangeField.Designer.cs
- src/Data/Migrations/20210728134138_AlterDetectionsChangeField.cs
- src/Seeds/Data/detections.json
-change score type to float in MDetection
-change score type to float in MCreateDetection
-change score type to float in EDetection
-ensure a migration was created
[HER-104](https://nerds-interns.atlassian.net/browse/HER-104?atlOrigin=eyJpIjoiYWE4MjY2NzI3NDYxNDZmNDk3ZWIxNzgwM2Y1ZmNhZjciLCJwIjoiaiJ9)
> [HER-104] Change score type to float

- src/Presentation/Detection/Fetching/Factory.cs
- src/Presentation/Detection/Fetching/Resolver.cs
- src/Presentation/Detection/Fetching/Types/TPDetection.cs
- src/Presentation/GraphQL/Base/Query.cs
- it should live inside the Presentation layer
- it will contain the following fields: id, score, class, timestamp, pagination, camera id
[HER-101](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-101)
> [HER-101] Create detection graph parameter

- src/Presentation/Camera/Fetching/Types/TPCamera.cs
[HER-109](https://nerds-interns.atlassian.net/browse/HER-109?atlOrigin=eyJpIjoiNzE4MzkzZmQwZTUxNDA1Yzg5OGU1ZjY4NGEwYzhlMmIiLCJwIjoiaiJ9)
> [HER-109] Make ids field nullable

- src/Business/Detection/Common/Repositories/IDetectionRepository.cs
- src/Business/Detection/Fetching/Commands/GetDetection.cs
- src/Business/Detection/Fetching/Commands/IGetDetection.cs
- src/Business/Pagination/Models/MPagination.cs
- src/Data/Detection/DetectionFactory.cs
- src/Data/Detection/DetectionRepository.cs
- src/Data/Pagination/CreatePagination.cs
- src/Presentation/Detection/Fetching/Factory.cs
- src/Presentation/Detection/Fetching/IResolver.cs
- src/Presentation/Detection/Fetching/Resolver.cs
- It will modify the Fetch method from the repository from detection
- It will contain a new method in detection factory for converting from MPagination<EDetection> in MPagination<MDetection>
[HER-106](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-106)
> [HER-106] Use pagination for detections

- src/Business/Camera/Common/Repositories/ICameraRepository.cs
- src/Business/Camera/Fetching/Commands/GetCameras.cs
- src/Business/Camera/Fetching/Commands/IGetCameras.cs
- src/Data/Camera/CameraFactory.cs
- src/Data/Camera/CameraRepository.cs
- src/Presentation/Camera/Fetching/Factory.cs
- src/Presentation/Camera/Fetching/IResolver.cs
- src/Presentation/Camera/Fetching/Resolver.cs
- src/Presentation/Camera/Fetching/Types/TPCamera.cs
- It will modify the Fetch method from the repository from camera
- It will contain a new method in detection factory for converting from MPagination<EDetection> in MPagination<MDetection> 
[HER-107](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-107)
> [HER-107] Use pagination for cameras

- Readme.md
It should contain the abbreviations and an explanation of what they are and where we use them.
[HER-112](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-112)
> [HER-112] Update readme file

- src/Presentation/Startup.cs
All the jira tickets related to the current pull request.
- [HER-137](https://nerds-interns.atlassian.net/browse/HER-137)
> [HER-137] Change cors configs

- src/Business/Detection/Fetching/Models/PDetection.cs
- src/Data/Detection/Filtering/DetectionFilter.cs
- src/Presentation/Detection/Fetching/Types/TPDetection.cs
- src/Seeds/Data/cameras.json
- src/Seeds/Data/detections.json
[HER-118](https://nerds-interns.atlassian.net/browse/HER-118?atlOrigin=eyJpIjoiMzIzMjk2YmExYmI1NGU3M2I0MjEzNWFkNTJlODAwMmYiLCJwIjoiaiJ9)
> [Her-118] Change cameraId filter to list

- src/Data/Camera/CameraFactory.cs
All the jira tickets related to the current pull request.
- [HER-143](https://nerds-interns.atlassian.net/browse/HER-143)
> [HER-143] Fix create detection mutation

- src/Business/Camera/Fetching/Models/PCamera.cs
- src/Business/Camera/Fetching/Models/PLatitude.cs
- src/Business/Camera/Fetching/Models/PLongitude.cs
- src/Data/Camera/CameraFactory.cs
- src/Data/Camera/Filtering/CameraFilter.cs
- src/Presentation/Camera/Fetching/Types/TPCamera.cs
- src/Presentation/Camera/Fetching/Types/TPLatitude.cs
- src/Presentation/Camera/Fetching/Types/TPLongitude.cs
- Add latitude and longitude filter
- Create latitude and longitude models and types
- Change camera filter
[HER-129](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-129)
> [HER-129] Enhance camera filters

- src/Data/Camera/CameraFactory.cs
Fix detection bug
[HER-147](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-147)
> [HER-147] Fix detection mutation

- src/Data/Camera/Filtering/CameraFilter.cs
- src/Data/Detection/Filtering/DetectionFilter.cs
[HER-150](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-150)
> [HER-150] Add fuzzy search for camera Ids

- src/Data/Camera/Filtering/CameraFilter.cs
- src/Data/Data.csproj
- src/Data/Detection/Filtering/DetectionFilter.cs
- Fix fuzzy search so it returns the cameras when you write a substring of the full id
[HER-153](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-153)
> [HER-153] Fix fuzzy search

- src/Presentation/Properties/launchSettings.json
[HER-160](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-160)
> [HER-160] Make the browser not open when running the program
